source-config: # PostgreSQL
  dialect: postgresql
  driver: PostgreSQL Unicode
  connection:
    host: localhost  
    port: 5432
    database: postgres
    username: postgres  
    password: ***  
    schema: ods

SqlServer:
  dialect: mssql+pyodbc
  driver: ODBC Driver 17 for SQL Server
  connection:
    host: localhost 
    port: 1433 
    database: IHG
    username: *****  
    password: ***

staging: # PostgreSQL
  dialect: postgresql
  driver: PostgreSQL Unicode
  connection:
    host: localhost
    port: 5432
    database: ETL
    username: postgres  
    password: ***  
    schema: stg

dwh: # PostgreSQL
  dialect: postgresql
  driver: PostgreSQL Unicode
  connection:
    host: localhost 
    port: 5433
    database: postgres
    username: ***  
    password: ***  
    schema: dwh

clickhouse:
  dialect: clickhouse
  driver: 
  connection:
    host: localhost 
    port: 8123
    database: 
    username: 
    password: 

clickhouse-tcp: 
  dialect: clickhouse
  driver: 
  connection:
    host: localhost
    port: 9000
    database: 
    username: 
    password: 


MySQL:
  dialect: mysql+pymysql
  driver: MySQL
  connection:
    host: localhost
    port: 3306
    database: db
    username: root
    password: **

PostgreSQL:
  dialect: postgresql
  driver: PostgreSQL Unicode
  connection:
    host: localhost
    port: 5432
    database: db
    username: postgres
    password: ***


